baseURL = "https://february2026calendarideas.online/"
languageCode = "en-us"
title = "February 2026 Calendar Ideas: Crafts, Holidays & Coloring"
theme = "PaperMod"

enableRobotsTXT = true
canonifyURLs = false

[pagination]
  pagerSize = 10

pygmentsUseClasses = true
pygmentsCodeFences = true

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[permalinks]
  blog = "/blog/new-khdrp-:slug-apsef-trends/"

[params]
  env = "production"
  title = "February 2026 Calendar Ideas: Crafts, Holidays & Coloring"
  author = "William Howell"
  customCSS = ["css/custom.css"]
  ShowTitle = true
  defaultTheme = "auto"

  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = false
  disableScrollToTop = false
  comments = false

  [params.label]
    text = "February 2026 Calendar Ideas"

  [params.profileMode]
    enabled = false

[menu]

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 2

[[menu.main]]
  name = "Privacy Policy"
  url = "/privacy-policy/"
  weight = 3

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 4

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 5

[taxonomies]
  category = "categories"
  tag = "tags"
